net: Fix macro for XCC
NET_SOCKET_GET_NAME macro adds some extra parenthesis that, on XCC (based
on GCC 4.2) ends up in the generated assembly, thus causing `as` to error
with:

  Error: junk at end of line, first unrecognized character is `('

It appears that the parenthesis are actually concatenated to the
generated name for identifier. This patch just removes them.

Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>