Bluetooth: Host: Fix build error with observer-only config
VELAPLATFO-78367

When building an observer-only build the check_pending_conn label would
result in CI warnings/errors due to this only being a C23 feature:

scan.c:692:1: error: label at end of compound statement is a C23 extension

Turns out the #ifdefs are completely unnecessary, and the code can simply
take advantage of IS_ENABLED(), which should get rid of the warning.

Change-Id: Ie04575efcc20c7b697aaa0ef2c8ad7d5c746b86f
Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
Signed-off-by: miot-robot <miot-robot@xiaomi.com>