drivers: ipm: ipm_mbox: Initialize after mbox drivers
This driver depends on its mboxes to be initialized, or the build
will fail like this:

ERROR: Device initialization priority validation failed, the sequence of \
       initialization calls does not match the devicetree dependencies.
ERROR: /ipm <ipm_mbox_init> is initialized before its dependency \
       /mailbox0@31f80000 <omap_mailbox_0_init> (POST_KERNEL+0 < \
       POST_KERNEL+2)

Lift its priority to device level.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>