sem/nuttx: fix nx_x API moved from function to inline.
VELAPLATFO-80448

external/zblue/zblue/port/kernel/sem.c:70:(.text.k_sem_take+0x8a): undefined reference to `nxsem_timedwait_uninterruptible'

Change-Id: Ie60faf1347a0dad5a764e094df2d11de10d5075d
Signed-off-by: buxiasen <buxiasen@xiaomi.com>