sem/nuttx: fix nx_x API moved from function to inline.
external/zblue/zblue/port/kernel/sem.c:70:(.text.k_sem_take+0x8a): undefined reference to `nxsem_timedwait_uninterruptible'

Signed-off-by: buxiasen <buxiasen@xiaomi.com>